### PR TITLE
suggestion: plot a powercurve

### PR DESCRIPTION
**Pull request by weibelzahl**
Dear heliosdrm,

I created a new S3 method plot.power.htest() and added it to the pwr package. This was inspired by GPower who provide a similar plot that allows to inspect how the test power depends on sample size.

The function works for all pwr.X.test() calls in pwr expect for pwr.f2.test() which doesn't use a sample size argument, so this type of diagram is not applicable.

I also created the respective man file.

I am not sure whether submissions to this package from external authors are accepted at all, but I thought I should give it a try. This is the first time I am creating a package, so I might have missed out on some conventions or requirements. The code can be optimized further in particular in regard to error handling which I'd be happy to do.

I have further possible extentions of this function in mind, including support for cohen.ES(), which also creates a power.htest object and more options for rendering, currently only xlab, ylab and main can be configured.

Beste Gruesse
Stephan.

### CODE REVIEW

**Comment by heliosdrm** [comment]
Dear Stephan.

Contributions like this are very welcome, specially pull requests as you have done, thank you. I have looked at the examples and the result is very nice. I'll revise it more carefully in the following days, and will take it into account for the next release of the package.

**Comment by weibelzahl** [comment]
Hi Helios,

thanks for the quick response. I am more than happy to improve the code if
you tell me what needs to be changed.

Otherwise, I will think about further additions along the lines of what I
mentioned before
- a barplot visualizing the results oF cohen.ES() (

**Comment by weibelzahl** [comment]
Hi Helios,

thanks for the quick response. I am more than happy to improve the code if
you tell me what needs to be changed.

Otherwise, I will think about further additions along the lines of what I
mentioned before
- a barplot visualizing the results of cohen.ES() (seems very
  straightforward)
- further configuration arguments for the plots

Beste Gruesse
Stephan.

**Comment by heliosdrm** [comment]
Hi Stephan. Version 1.1-4 of the package has just been published in CRAN, including your new function. Thanks for your contribution.

**Pull request merged**
